import Head from 'next/head';
import Link from 'next/link';
import { GetStaticProps, InferGetStaticPropsType } from 'next';
import { Fragment } from 'react';
import { Footer } from '../components/Footer/Footer';
import { Card } from '../components/Card/Card';
import { Article } from '../generated/payload-types';
import { CMS_API } from '../config';

interface Props {
  articles: Article[];
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const response = await fetch(`${CMS_API}/articles`);
  const articles = await response.json();

  return {
    props: {
      articles: articles.docs,
    },
  };
};

export default function Home({
  articles,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const cards = articles?.map(article => {
    if (article === null) {
      return <Fragment key={0}></Fragment>;
    }

    return (
      <Card
        key={article.id}
        heading={article.title}
        body={''}
        link={article.seo_url}
      />
    );
  });

  return (
    <>
      <Head>
        <title>Reshipi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container max-w-screen-md mx-auto px-4 min-h-screen">
        <div className="min-h-[45vh]"></div>
        <h1 className="text-6xl mb-20 text-center font-light">
          <Link className="font-sans" href="/">
            reshipi
          </Link>
        </h1>

        <div className="flex flex-col">{cards}</div>
      </main>
    </>
  );
}
