import Head from 'next/head';
import Link from 'next/link';
import { gql } from '@apollo/client';
import { GetStaticProps, InferGetStaticPropsType } from 'next';
import { Fragment } from 'react';
import Footer from '../components/Footer/Footer';
import Card from '../components/Home/Card';
import client from '../apollo-client';
import { Articles } from '../__generated__/Articles';

export const getStaticProps: GetStaticProps<Articles> = async () => {
  const { data } = await client.query({
    query: gql`
      query Articles {
        articles {
          _id
          title
          seoDescription
          seoUrl
          body
        }
      }
    `,
  });

  return {
    props: {
      articles: data.articles,
    },
  };
};

export default function Home({
  articles,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const cards = articles?.map(article => {
    if (article === null) {
      return <Fragment key={0}></Fragment>;
    }

    return (
      <Card
        key={article._id}
        heading={article.title}
        body={article.body}
        link={article.seoUrl}
      />
    );
  });

  return (
    <>
      <Head>
        <title>Reshipi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="lg:container mx-auto px-4 mb-20">
        <h1 className="text-6xl my-8 text-center font-thin">
          Welcome to{' '}
          <Link href="/">
            <a className="text-blue-600">Reshipi</a>
          </Link>
        </h1>

        <div className="flex flex-col">{cards}</div>
      </main>

      <Footer />
    </>
  );
}
